# Generated by Django 5.2.7 on 2025-11-05 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plazo_dias', models.PositiveIntegerField(default=7)),
                ('max_prestamos_por_cliente', models.PositiveIntegerField(default=3)),
                ('mora_diaria', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
